version: '3'

services:
  app:
    build: ./app
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      TZ: JST
      DJANGO_SETTINGS_MODULE: res_system.settings_prod
    networks:
      app_net:
        ipv4_address: 172.30.0.30
  db:
    build: ./db
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: res_system
      MYSQL_ROOT_PASSWORD: BVvL$Fv/q1a8
      MYSQL_USER: worker
      MYSQL_PASSWORD: worker
      TZ: 'Asia/Tokyo'
    networks:
      app_net:
        ipv4_address: 172.30.0.31

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
