version: '3'

services:
  app:
    build: ./app
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      TZ: JST
      DJANGO_SETTINGS_MODULE: res_system.settings_prod
  db:
    build: ./db
    #user: "1000:50"
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: res_system
      MYSQL_ROOT_PASSWORD: Password
      MYSQL_USER: worker
      MYSQL_PASSWORD: worker
      TZ: 'Asia/Tokyo'
